{"pageProps":{"questions":[{"id":"wxx3sidpCVb9L5y1BHtG","topic":"1","question_text":"What is the expected output of the following code?\n//IMG//","question_id":61,"isMC":true,"answer":"B","question_images":["https://www.examtopics.com/assets/media/exam-media/04235/0002000002.jpg"],"answer_description":"","exam_id":192,"answers_community":["B (100%)"],"discussion":[{"poster":"starmario12","upvote_count":"9","content":"strings are immutable, B","timestamp":"1621690560.0","comment_id":"363708"},{"content":"Selected Answer: B\nstrings are immutable","timestamp":"1728588780.0","upvote_count":"1","poster":"megan_mai","comment_id":"1295727"},{"content":"Selected Answer: B\nCorrect: B\nstr = 'abcdef'\ndef fun(s):\n del s[2]\n return s\n\nprint(fun(str)) #TypeError: 'str' object doesn't support item deletion","poster":"JeyTlenJey","comment_id":"1256573","timestamp":"1722137280.0","upvote_count":"1"},{"poster":"macxsz","timestamp":"1651534320.0","content":"Selected Answer: B\nB. The program will cause a runtime exception/error","comment_id":"596256","upvote_count":"1"}],"url":"https://www.examtopics.com/discussions/python-institute/view/53344-exam-pcap-topic-1-question-26-discussion/","choices":{"D":"abdef","B":"The program will cause a runtime exception/error","C":"acdef","A":"abcef"},"unix_timestamp":1621690560,"timestamp":"2021-05-22 15:36:00","answer_images":[],"answer_ET":"B"},{"id":"Bmx6EZVzahTFB4XuMHws","timestamp":"2021-04-05 13:24:00","topic":"1","question_images":["https://www.examtopics.com/assets/media/exam-media/04235/0002200001.jpg"],"answer_images":["https://www.examtopics.com/assets/media/exam-media/04235/0002200002.png"],"unix_timestamp":1617621840,"exam_id":192,"question_id":62,"choices":{"C":"3","B":"2","A":"21","D":"12"},"discussion":[{"comment_id":"597548","upvote_count":"1","poster":"666_m","timestamp":"1651811280.0","content":"A is correct"},{"content":"Selected Answer: A\nanswer:\nA. 21","upvote_count":"2","poster":"macxsz","timestamp":"1651534380.0","comment_id":"596257"},{"poster":"Efren","comment_id":"328599","content":">>> def f(n):\n... if n==1:\n... return'1'\n... return str(n)+f(n-1)\n...\n>>> print(f(2))\n21","timestamp":"1617621840.0","upvote_count":"4"}],"url":"https://www.examtopics.com/discussions/python-institute/view/49184-exam-pcap-topic-1-question-27-discussion/","answer_ET":"A","isMC":true,"question_text":"What is the expected output of the following code?\n//IMG//","answers_community":["A (100%)"],"answer":"A","answer_description":""},{"id":"9nvSHtcjkmv8vQF1tKY5","answer":"D","url":"https://www.examtopics.com/discussions/python-institute/view/28254-exam-pcap-topic-1-question-28-discussion/","answer_description":"","timestamp":"2020-08-12 13:13:00","discussion":[{"comment_id":"156358","timestamp":"1597230780.0","poster":"clacot","comments":[{"content":"Because during an assignment, the RHS is evaluated first and the result is assignment to the given identifier. In this case, the `x` on the RHS was a function and the result (1 + x() = 1 + 2) was REASSIGNED/BOUND to the same identifier. Post reassignment, x is bound to a int literal, while before it was bound to a function.\n\nI hope this snippet will help: https://prnt.sc/u1u8ki","comments":[{"timestamp":"1597837320.0","comment_id":"161466","upvote_count":"1","content":"clear now. Thanks!","poster":"clacot"}],"comment_id":"161052","poster":"lasagne394","timestamp":"1597774020.0","upvote_count":"12"}],"upvote_count":"5","content":"I know we shouldn't use function name same as variable name. But if I run the code the result is 3. Why?"},{"poster":"Deeksha__Jain","upvote_count":"1","content":"Selected Answer: D\nSelected Answer: D","timestamp":"1740389640.0","comment_id":"1360960"},{"content":"Selected Answer: D\ndef x(): #x_function\n return 2\nx=1+x() #x_value=use x_function\nprint(x) #-->3\n\ndef x(): #x_function\n return 2\nx=10 #x_value=int\nx=1+x() #x_value=use not exist x_function\nprint(x) #-->TypeError: 'int' object is not callable","timestamp":"1705835640.0","upvote_count":"1","poster":"natlal","comment_id":"1127769"},{"timestamp":"1696028940.0","upvote_count":"1","comment_id":"1021093","content":"D.prints 3","poster":"34_trt"},{"upvote_count":"1","comment_id":"596258","timestamp":"1651534680.0","content":"Selected Answer: D\nD. print 3","poster":"macxsz"},{"poster":"wolverin3","comment_id":"221828","timestamp":"1605699960.0","upvote_count":"1","content":"def x(i):\n print(i)\n return i\nx=x(1)+x(2)\nExpression is evaluated from left to right, function return takes more precedence then followed by operator and finally value is assigned which is of least precedence. Above example would illustrate it."}],"topic":"1","question_text":"What is the expected behavior of the following snippet?\n//IMG//\n\nIt will:","choices":{"B":"cause a runtime exception on line 01","D":"print 3","C":"cause a runtime exception on line 03","A":"cause a runtime exception on line 02"},"exam_id":192,"unix_timestamp":1597230780,"question_id":63,"isMC":true,"question_images":["https://www.examtopics.com/assets/media/exam-media/04235/0002300001.jpg"],"answers_community":["D (100%)"],"answer_ET":"D","answer_images":[]},{"id":"u7fmoVuSWIF0fzVaFl3F","question_text":"What is the expected behavior of the following code?\n//IMG//\n\nIt will:","url":"https://www.examtopics.com/discussions/python-institute/view/41805-exam-pcap-topic-1-question-29-discussion/","question_id":64,"exam_id":192,"discussion":[{"poster":"hackadocka","comments":[{"content":"It works for me even is i and I, check my code up","comment_id":"339050","poster":"Efren","timestamp":"1618856400.0","upvote_count":"2"},{"comment_id":"341090","timestamp":"1619098200.0","upvote_count":"4","content":"the capital I would cause an error if you were to iterate through actual generator obj, for example in [for i in f(2)] there would be a NameError. However, in this code the obj is never ran so no error occurs.","poster":"koyuul"}],"content":"yield keyword expression is I (capital i), while for loop variable is i (small I). Function is erroneous.","comment_id":"262331","timestamp":"1610082300.0","upvote_count":"7"},{"content":">>> def f(n):\n... for i in range (1,n+1):\n... yield I\n...\n>>> print(f(2))\n<generator object f at 0x0000013BA21A82A0>\n\nANswer is correct","poster":"Efren","comment_id":"337587","upvote_count":"6","timestamp":"1618663860.0"},{"timestamp":"1740389760.0","comment_id":"1360961","upvote_count":"2","poster":"Deeksha__Jain","content":"Selected Answer: C\nSelected Answer: C"},{"poster":"zantrz","upvote_count":"3","content":"Selected Answer: B\ndef f(n):\n for i in range(1,n+1):\n yield i\n\nprint(f(2)) #output: <generator object f at 0x000001C77ED4D000>\ngenerator=f(2)\nprint(next(generator)) #output: 1\nprint(next(generator)) #output: 2\nprint(next(generator)) #output: StopIteration","timestamp":"1707822840.0","comment_id":"1149113"},{"timestamp":"1707207900.0","poster":"Oracleist","content":"yield control the flow of a generator.\nthan if we use I instead of the variable name i, it will return an object that represent a generator.","upvote_count":"1","comment_id":"1141936"},{"content":"Selected Answer: B\ndef f(n):\n for i in range(1,n+1):\n yield i\nprint(f(2)) #<generator object f at 0x00000220062CB140>\n\nfor x in f(2):\n print(x, end='') #12\n\n\ndef f(n):\n for i in range(1,n+1):\n yield I\nfor x in f(2):\n print(x, end=' ') #NameError: name 'I' is not defined","poster":"natlal","upvote_count":"1","comment_id":"1127774","timestamp":"1705837620.0"},{"content":"Yield I is not the same as the variable name i. Which should mean runtime error.","timestamp":"1686741420.0","upvote_count":"3","poster":"Ello2023","comment_id":"923029"},{"timestamp":"1677502440.0","poster":"mlsc01","comment_id":"823685","content":"Selected Answer: B\nThe NameError is not raised because the generator is not executed at all. It's defined and only its reference is used. If it is executed in a loop or comprehension or by using next() then only the NameError will be raised.","upvote_count":"2"},{"content":"yield automatically creates, __iter__() and next() function. assuming it was yeild i. \nthen to print, we would need print(next(f(2)))","upvote_count":"1","comment_id":"795675","timestamp":"1675302600.0","poster":"CAPTAINKURK"},{"content":"Selected Answer: B\nThis question is SO TRICKY. yield I, or yield X or yield ANYTHING, doesn't matter because in the code the undefined variable \"I\" is never reached. As the answer below from TheNetworkStudent, the answer is B.","comment_id":"690383","poster":"ivanbicalho","timestamp":"1665335820.0","upvote_count":"2"},{"timestamp":"1658183040.0","poster":"PremJaguar","comment_id":"633179","content":"Selected Answer: C\nanswer is c because variable names are case sensitive","upvote_count":"1"},{"poster":"macxsz","upvote_count":"1","content":"Selected Answer: B\nB. print <generator object f at (some hex digits)>","comment_id":"596338","timestamp":"1651578060.0"},{"timestamp":"1646482140.0","content":"Selected Answer: B\nif you try to loop through the generator, it will error. This won't happen because it's simply printed. Code is erroneous, but won't result in an error if executed in this manner.\n\nAnswer B is correct.","upvote_count":"4","poster":"TheNetworkStudent","comment_id":"561412"},{"poster":"vidts","comment_id":"331020","timestamp":"1617872400.0","content":"answer is correct","upvote_count":"2"}],"answer":"B","question_images":["https://www.examtopics.com/assets/media/exam-media/04235/0002400002.jpg"],"isMC":true,"unix_timestamp":1610082300,"timestamp":"2021-01-08 06:05:00","answer_images":[],"choices":{"C":"cause a runtime exception","A":"print 4321","B":"print <generator object f at (some hex digits)>","D":"print 1234"},"answer_ET":"B","topic":"1","answers_community":["B (81%)","C (19%)"],"answer_description":""},{"id":"a3lx2KO5Ago1he8zReY9","question_text":"What will the value of the i variable be when the following loop finishes its execution?\n//IMG//","url":"https://www.examtopics.com/discussions/python-institute/view/16126-exam-pcap-topic-1-question-3-discussion/","answer":"D","question_id":65,"timestamp":"2020-03-10 16:53:00","answer_images":[],"exam_id":192,"answer_ET":"D","discussion":[{"comment_id":"61797","comments":[{"timestamp":"1610955600.0","upvote_count":"6","content":"Just try to print the value of i after the loop, you would get 9 as result.\n\n<code>\nfor i in range(10):\n pass\nprint(i)\n</code>","poster":"Dushank","comment_id":"270077"}],"poster":"Avidulam","timestamp":"1583855580.0","content":"The answer is 9.","upvote_count":"25"},{"content":"9 is the Answer. Pass only means there are no statements to execute it does not means the variable is unavailable. Try a Print statemnt Print(i) after the For Loop and there is your result.","upvote_count":"12","comment_id":"70774","poster":"HarrySoni","comments":[{"comment_id":"152532","content":"Correct","upvote_count":"2","poster":"imsaad","timestamp":"1596803220.0"}],"timestamp":"1585924080.0"},{"timestamp":"1739869860.0","upvote_count":"1","poster":"_vt","comment_id":"1358198","content":"Selected Answer: D\nSelected Answer: D. 9"},{"content":"Selected Answer: D\nAnswers are CD\nfor i in range (10):\n pass\nprint(i)\n#output: 9","upvote_count":"1","timestamp":"1728569640.0","poster":"megan_mai","comment_id":"1295626"},{"comment_id":"1227747","upvote_count":"1","timestamp":"1718007000.0","content":"Selected Answer: D\nI'm seeing answer B, C and D in the comments ... strange ?","poster":"86b907f"},{"poster":"Dempsdawg","timestamp":"1711024800.0","upvote_count":"1","comment_id":"1179217","content":"Selected Answer: B\nfor i in range(10):\n pass #This pass will make it C because there is NO print function"},{"timestamp":"1711024740.0","upvote_count":"1","poster":"Dempsdawg","content":"Selected Answer: C\nfor i in range(10):\n pass\n\nSub pass for print(i):\n0\n1\n2\n3\n4\n5\n6\n7\n8\n9","comment_id":"1179214"},{"content":"C:\\Python_Local\\Python_CMD\\PCAP>more pcep1.py\nfor i in range(10):\n pass\n print(i)\n\n\nC:\\Python_Local\\Python_CMD\\PCAP>python pcep1.py\n0\n1\n2\n3\n4\n5\n6\n7\n8\n9\n\nC:\\Python_Local\\Python_CMD\\PCAP>","timestamp":"1706534580.0","comment_id":"1134980","poster":"Irgond07","upvote_count":"1"},{"poster":"eskimolight","content":"Can someone confirm if this exam code is PCAP-31-03 ?","upvote_count":"2","timestamp":"1700704260.0","comment_id":"1077977"},{"upvote_count":"1","poster":"Bere","timestamp":"1698349080.0","comment_id":"1054874","content":"Selected Answer: D\nfor i in range(10):\n print(f\"for-i: {i}\")\n pass\n\nprint(f\"final-i: {i}\")\n\nfor-i: 0\nfor-i: 1\nfor-i: 2\nfor-i: 3\nfor-i: 4\nfor-i: 5\nfor-i: 6\nfor-i: 7\nfor-i: 8\nfor-i: 9\nfinal-i: 9"},{"upvote_count":"1","timestamp":"1694144040.0","poster":"KentuckyFriedRice","comment_id":"1002066","content":"The answer is B because i is an interation variable. Once the loop has finished execution, it is no longer accessible."},{"poster":"mplopez","comment_id":"959551","content":"Selected Answer: D\nThe for loop start to count from 0 and de range of members that must to iterate are 10 loops, that says the loop begins in 0 and finish in 9.","timestamp":"1690032060.0","upvote_count":"1"},{"upvote_count":"1","comment_id":"905396","content":"Answer is 9","poster":"DrMKG","timestamp":"1684891260.0"},{"content":"Selected Answer: D\nAnswer : D : 9","comment_id":"892278","upvote_count":"1","poster":"Sadaiyan","timestamp":"1683558420.0"},{"comment_id":"832598","poster":"Dinsha","content":"Selected Answer: D\nAnswer 9","upvote_count":"1","timestamp":"1678257180.0"},{"poster":"spiderking123","content":"Selected Answer: D\nThe answer is 9","comment_id":"829538","timestamp":"1677981600.0","upvote_count":"1"},{"timestamp":"1674564540.0","upvote_count":"1","poster":"Blippen","comment_id":"786531","content":"Selected Answer: D\n9 in the answer"},{"timestamp":"1670774040.0","content":"D is the right answer. The value of the i variable when the for loop finishes its execution will be 9. This is because the range(10) function generates a sequence of numbers from 0 to 9, and the for loop will iterate over this sequence, with the variable i taking on each value in turn. When the for loop reaches the end of the sequence, it will stop, and the value of i at that point will be 9.","upvote_count":"2","comment_id":"741865","poster":"Adeshina"},{"comment_id":"659019","upvote_count":"1","poster":"ciccio_benzina","content":"it's 9!","timestamp":"1662275040.0"},{"poster":"alfonsocav1982","upvote_count":"1","comment_id":"652997","timestamp":"1661698860.0","content":"9 in the answer"},{"content":"I think we'd better use original code instead of adding \"print(i)\" after pass , since in the question there is no \"print(i)\" included~ if I just simply run the given code~ nothing shows up~","comment_id":"615074","upvote_count":"1","poster":"Jajalmao","timestamp":"1654978860.0"},{"timestamp":"1654007340.0","content":"All I want to know is what is the answer in the PCAP exam?\nIf you use an indented print statement , in place of the pass, 0 1 2 3 4 5b 6 7 8 9 is returned. i is an iterable object a one time iteration, if you leave the pass statement, and include a print statement print(i) in the IDLE after the pass and in line with th for(meaning not indented nothing prints, so i is unavailable, its a one time loop and not saved.","upvote_count":"1","poster":"Janpcap123","comment_id":"609771"},{"comment_id":"602382","content":"B is correct","timestamp":"1652675220.0","upvote_count":"1","poster":"666_m"},{"upvote_count":"1","content":"Answer is 9. Pass is an isntruction that means 'do nothing', but the variable is increased in every loop.\nTry to execute the code","comment_id":"599667","timestamp":"1652197140.0","poster":"Juanka1974"},{"comment_id":"597123","poster":"666_m","timestamp":"1651727820.0","upvote_count":"1","content":"B is correct"},{"upvote_count":"1","poster":"macxsz","content":"answer:\nD. 9","comment_id":"596222","timestamp":"1651525980.0"},{"content":"Selected Answer: D\nYes, 9 is the answer.\nYou can try this code on your computer.","upvote_count":"1","timestamp":"1651055640.0","comment_id":"593061","poster":"hibana2077"},{"poster":"Ram5678","timestamp":"1650943620.0","comment_id":"592065","upvote_count":"1","content":"The answer is 9."},{"upvote_count":"1","content":"Selected Answer: D\nThe answer is 9.","comment_id":"558672","poster":"Kuzymir","timestamp":"1646124000.0"},{"comment_id":"555468","upvote_count":"1","content":"Selected Answer: D\nIf this were run in a function, B would be correct because the value of 'i' does not get returned to the main program; however, if run in the shell, it will return a value of '9' for 'i'. To prove, set i = None prior to the loop, then run the loop, outside the loop print(i) gives value '9'; if the loop is set in a function, regardless of whether the function is run, print(i) would give value 'None'.","poster":"arizz","timestamp":"1645726260.0"},{"content":"Selected Answer: D\nIf you try it in the terminal the answer turns out to be 9","poster":"karans","timestamp":"1644278400.0","upvote_count":"1","comment_id":"542769"},{"timestamp":"1642390500.0","poster":"diazed","upvote_count":"1","content":"Selected Answer: D\nThe answer is 9","comment_id":"525439"},{"upvote_count":"2","comment_id":"517941","content":"B. is correct because it says the name pass isn't identified","timestamp":"1641442020.0","poster":"Developer2215"},{"upvote_count":"1","content":"Selected Answer: D\nprint 9 after for loop. it will print 9","poster":"technoguy","comment_id":"488331","timestamp":"1638034140.0"},{"upvote_count":"2","poster":"technoguy","content":"the correct answer is D i.e, 9. \ntry to print i after for loop","timestamp":"1638033960.0","comment_id":"488326"},{"poster":"pyexp21","comment_id":"447646","timestamp":"1632060540.0","content":"The answer is D","upvote_count":"1"},{"content":"Guys, just to clarify everybody's douts: Try to execute the following:\n\nfor i in range(10):\n pass\n print(i)\n\nAnd you will see that even if there is a 'pass' in the loop, the print inside the while, show that 'i' object is sequentially iterable by the range of 10, starting from '0' to '9'.","poster":"jenper","upvote_count":"1","comment_id":"427563","timestamp":"1629388620.0"},{"content":"B is the correct one coz 'pass' is used as a placeholder for future execution but currently returning nothing \"null\"","timestamp":"1608805200.0","comment_id":"251538","upvote_count":"2","poster":"cmcharles3"},{"content":"The answer is 9. Replace the \"pass\" with below code and see result. \n\nfor i in range (10):\n print('I = ' + str(i))\nprint(i)","upvote_count":"1","comment_id":"244758","poster":"_adem","timestamp":"1608051240.0"},{"comment_id":"233102","content":"Could be 9 the answer but in the example there isn't a \"print(i)\" so i think the correct answer is B","upvote_count":"2","timestamp":"1606921500.0","poster":"guidoleonardo"},{"comment_id":"218293","content":"The answer is 9","timestamp":"1605246240.0","poster":"shantanup","upvote_count":"1"},{"comment_id":"204883","content":"The answer is with no doubts 'D. 9'\nJust run it in python's shell","upvote_count":"1","poster":"FR99","timestamp":"1603502040.0"},{"timestamp":"1600082400.0","comment_id":"179234","poster":"Nehuuu","content":"Answer is 9","upvote_count":"2"},{"content":"Everyone say that write print(i).But this question I dont see print function.Without print function nothing return","timestamp":"1599763380.0","poster":"elibrahimov396","upvote_count":"2","comments":[{"poster":"KC","content":"But B is incorrect, because you can still print i outside of the loop, so the variable is available.","upvote_count":"1","timestamp":"1608074700.0","comment_id":"245037"}],"comment_id":"177285"},{"timestamp":"1599537300.0","poster":"jarvisasim","upvote_count":"1","comment_id":"175590","content":"Yes, 9 is answer."},{"upvote_count":"1","comment_id":"172841","timestamp":"1599155220.0","content":"9 is the answer","poster":"Spectra"},{"upvote_count":"1","comment_id":"167501","poster":"kauser","timestamp":"1598529060.0","content":"Answer is D. 9. \nTo check: \nCreate a print variable that prints once the loop is finished and that gives you 9."},{"timestamp":"1598528940.0","content":"Answer is D","poster":"kauser","upvote_count":"2","comment_id":"167500"},{"timestamp":"1597611540.0","upvote_count":"1","poster":"Truth","comment_id":"159457","content":"The answer is 9. Does anyone know who is actually responsible for providing the answers that appear for the \"Solution\"? Wow!"},{"poster":"NLP","comment_id":"155784","upvote_count":"1","content":"The answer is 9","timestamp":"1597173600.0"},{"poster":"WorkingDaddy","timestamp":"1593965040.0","comment_id":"126966","content":"The reference to pass is a little misleading since instead of pass, you can put ANYthing there (that does not affect the variable i).","upvote_count":"1"},{"comment_id":"74016","timestamp":"1586770620.0","poster":"iyke2k4","upvote_count":"3","content":"I can see most people answered 9. I tried to print 'i' from a Python compiler and I got 9 too. Does it mean that the answer is wrong from this site?"},{"content":"The correct answer is: \nB- The variable becomes unavailable","comment_id":"66109","timestamp":"1584652440.0","poster":"Zeehay","upvote_count":"1"},{"comment_id":"66107","poster":"Zeehay","upvote_count":"1","content":"The answer is B:","timestamp":"1584652320.0"},{"poster":"CERTIFICATION1990","content":"The answer is 9.","upvote_count":"5","timestamp":"1584300300.0","comment_id":"64443"}],"unix_timestamp":1583855580,"choices":{"B":"the variable becomes unavailable","D":"9","A":"10","C":"11"},"isMC":true,"question_images":["https://www.examtopics.com/assets/media/exam-media/04235/0000400001.jpg"],"topic":"1","answer_description":"","answers_community":["D (88%)","6%"]}],"exam":{"numberOfQuestions":141,"isImplemented":true,"id":192,"isBeta":false,"provider":"Python-institute","lastUpdated":"12 Apr 2025","name":"PCAP","isMCOnly":false},"currentPage":13},"__N_SSP":true}